# Generated by Django 3.2.9 on 2023-06-03 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexedPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_id', models.CharField(max_length=255)),
                ('search_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deal_search.searchrequest')),
            ],
        ),
    ]
